name: flutter_monster
description: A new Flutter application for mobile monster.
author: Guo Rui <guorui@microduino.cc>

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.22+15

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^0.4.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.3
  rxdart: ^0.18.1
  dio: ^2.0.4
  oktoast: ^2.1.5
  cached_network_image: ^0.8.0
  url_launcher: ^4.0.1
  flutter_easyrefresh: ^1.2.7
  flutter_swiper: ^1.1.4
  flutter_bridge_webview: ^0.1.31
  sharesdk: ^1.0.9
  gt3: ^0.0.5
  sprintf: ^4.0.0
  flutter_blue: ^0.5.0
  permission_handler: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/
#    - assets/dist/
#    - assets/dist/asset/
#    - assets/dist/asset/static/
#    - assets/dist/static/
#    - assets/dist/static/groot/
#    - assets/dist/static/groot/hex/
#    - assets/dist/static/blocks-media/
#    - assets/dist/static/blocks-media/extensions/
#    - assets/dist/static/blocks-media/icons/
#    - assets/dist/static/css/
#    - assets/dist/static/img/
#    - assets/dist/static/fonts/
#    - assets/dist/static/js/
#    - assets/dist/static/mdesigner/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
